name: EftMainSystem
version: '${version}'
main: com.ulxsth.eftmainsystem.EftMainSystem
api-version: 1.19
commands:
  record:
    aliases: [record]
    description: "これまでのデータを確認します"
  stats:
    aliases: [stats]
    description: "所持金を確認します"
  pay:
    aliases: [pay]
    description: "ほかのプレイヤーにお金を渡します"
